name: simple-db
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2022.12.7=h033912b_0
  - libffi=3.4.2=h0d85af4_5
  - libsqlite=3.40.0=ha978bb4_0
  - libzlib=1.2.13=hfd90126_4
  - ncurses=6.3=h96cf925_1
  - openssl=3.0.8=hfd90126_0
  - pip=23.0=pyhd8ed1ab_0
  - python=3.10.9=he7542f4_0_cpython
  - readline=8.1.2=h3899abd_0
  - setuptools=67.1.0=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - tzdata=2022g=h191b570_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - pip:
      - ads==0.12.3
      - asdf==2.14.3
      - asdf-astropy==0.3.0
      - asdf-coordinates-schemas==0.1.0
      - asdf-standard==1.0.3
      - asdf-transform-schemas==0.3.0
      - asdf-unit-schemas==0.1.0
      - asdf-wcs-schemas==0.1.1
      - astrodbkit2==0.5.1
      - astropy==5.2.1
      - astroquery==0.4.6
      - attrs==22.2.0
      - beautifulsoup4==4.11.2
      - certifi==2022.12.7
      - charset-normalizer==3.0.1
      - exceptiongroup==1.1.0
      - greenlet==2.0.2
      - gwcs==0.18.3
      - html5lib==1.1
      - httpretty==0.8.10
      - idna==3.4
      - importlib-metadata==6.0.0
      - iniconfig==2.0.0
      - jaraco-classes==3.2.3
      - jmespath==1.0.1
      - jsonschema==4.17.3
      - keyring==23.13.1
      - markupsafe==2.1.2
      - mock==5.0.1
      - more-itertools==9.0.0
      - ndcube==2.0.3
      - numpy==1.24.2
      - packaging==23.0
      - pandas==1.5.3
      - pluggy==1.0.0
      - pyerfa==2.0.0.1
      - pyrsistent==0.19.3
      - pytest==7.2.1
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - pyvo==1.4
      - pyyaml==6.0
      - requests==2.28.2
      - scipy==1.10.0
      - semantic-version==2.10.0
      - six==1.16.0
      - soupsieve==2.3.2.post1
      - specutils==1.9.1
      - sqlalchemy==2.0.3
      - tomli==2.0.1
      - tqdm==4.64.1
      - typing-extensions==4.4.0
      - urllib3==1.26.14
      - webencodings==0.5.1
      - werkzeug==2.2.2
      - zipp==3.13.0
